apiVersion: apps/v1
kind: Deployment
metadata:
  name:  testingapp
  namespace: default
  labels:
    app:  testingapp
spec:
  selector:
    matchLabels:
      app: testingapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  testingapp
    spec:
      containers:
        - name: testingapp
          image: deep1024/testing:latest
          ports:
            - containerPort: 5252